services:
  mimir:
    image: grafana/mimir:2.12.0
    container_name: mimir
    ports:
      - 9090:9090
    restart: unless-stopped
    command: --config.file=/etc/mimir.yaml
    volumes:
      - ./lgtm-configurations/mimir/mimir.yaml:/etc/mimir.yaml
      - ./lgtm-configurations/mimir/alertmanager.yaml:/etc/alertmanager-fallback-config.yaml
  loki:
    image: grafana/loki:3.1.0
    container_name: loki
    command: -config.file=/etc/loki/local-config.yaml
    environment:
      - JAEGER_AGENT_HOST=otelcol

  grafana:
    image: grafana/grafana:11.0.1
    container_name: grafana
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
    volumes:
      - ./lgtm-configurations/grafana/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
      # - ./lgtm-configurations/grafana/dashboard.yaml:/etc/grafana/provisioning/dashboards/main.yaml
      - ./lgtm-configurations/grafana/dashboards:/var/lib/grafana/dashboards
      # - ./lgtm-configurations/grafana/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - loki
      - tempo
      - mimir

  tempo:
    image: grafana/tempo:2.5.0
    container_name: tempo
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./lgtm-configurations/tempo/tempo.yaml:/etc/tempo.yaml

  ## Tools
  promtail:
    image: grafana/promtail:2.9.5
    container_name: promtail
    volumes:
      - /var/lib/docker/:/var/lib/docker:ro
      - ./lgtm-configurations/promtail/config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml

  otelcol:
    image: otel/opentelemetry-collector:0.104.0
    container_name: otelcol
    # restart: unless-stopped
    ports:
      - 4317:4317 # otlp grpc
      - 4318:4318 # otlp http
      - 8888:8888 # monitoring
    command: --config=/etc/otelcol/config.yaml
    depends_on:
      - loki
      - tempo
      - mimir
      - grafana
    volumes:
      - ./lgtm-configurations/otelcol/config.yaml:/etc/otelcol/config.yaml

  application:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: application
    restart: unless-stopped
    depends_on:
      - loki
      - tempo
      - mimir
      - grafana
    ports:
      - 0.0.0.0:8081:8081
    command: ["run", "start-with-tracing"]
    environment:
      - APP_PORT=8081
      - OTEL_COL_URL=otelcol
      - OTEL_COL_PORT=4318
      - OTEL_COL_PROTOCOL=http
    logging:
      driver: json-file
