name: Deploy

on:
  push:
    branches: [master]

jobs:
  Deploy:
    name: Deploy on EC2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Pull & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{secrets.USER_NAME}}
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            cd lgtm-proof-of-concept
            git fetch
            git pull
            docker compose up --build -d
            '
